[package]
name = "vimparq"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "55.0.0"
arrow-json = "55.0.0"
clap = { version = "4.5.37", features = ["derive"] }
parquet = "55.0.0"
serde_json = "1.0.140"
